### ISSUE TITLE
Create a function to get the surname of each passenger

### ISSUE THREAD

**Issue by shiyaol** [dsi-principles-prog/midterm-shiyaol#1]
**Why are we doing this**: For our numeric variables, we can get the surname of the passengaer.  Some rich families might have more chances to survive

**Hint: Use "strsplit" function in R**

**The input of the function: A dataframe**

**The output of the function: A dataframe with surnames and name the variable as "surname"**

For example, if the name of the passenger is "Braund, Mr. Owen Harris", you should extract "Braud" as the surname.

The surname variable should be like this:
![image](https://user-images.githubusercontent.com/42880105/67667350-9df55b00-f93b-11e9-9be5-28b07ad053b4.png)

**Comment by wadem117** [comment]
I'm pretty sure we did this differently because I had to adjust the assert statement to test the function, but the end result is the same.
